import { Event } from "@/core/models/Event";

export const EVENTS : Event[] = [
     {
       id: 1,
       title: "Concert de Rock",
       date: new Date(2023, 10, 15),
       time: "20:00",
       location: "Salle de Concert, Paris",
       capacity: 300,
       description: "Un concert live avec les meilleurs groupes de rock.",
       image: "rock_concert.jpg",
       category: { id: 1, title: "Concerts", description: "Événements musicaux en direct avec des artistes variés." },
     },
     {
       id: 2,
       title: "Exposition de Photographie",
       date: new Date(2023, 10, 20),
       time: "10:00",
       location: "Galerie d'Art, Lyon",
       capacity: 100,
       description: "Découvrez des œuvres de photographes contemporains.",
       image: "photo_exhibition.jpg",
       category: { id: 2, title: "Expositions", description: "Expositions d'art, de photographie et de culture." },
     },
     {
       id: 3,
       title: "Conférence sur l'Innovation",
       date: new Date(2023, 11, 5),
       time: "14:00",
       location: "Centre de Conférences, Marseille",
       capacity: 5,
       description: "Des experts discutent des dernières innovations technologiques.",
       image: "innovation_conference.jpg",
       category: { id: 3, title: "Conférences", description: "Conférences sur des sujets divers et variés." },
     },
     {
       id: 4,
       title: "Atelier de Cuisine",
       date: new Date(2023, 11, 10),
       time: "18:00",
       location: "École de Cuisine, Toulouse",
       capacity: 15,
       description: "Apprenez à cuisiner des plats délicieux.",
       image: "cooking_workshop.jpg",
       category: { id: 4, title: "Ateliers", description: "Ateliers pratiques pour développer de nouvelles compétences." },
     },
     {
       id: 5,
       title: "Match de Football",
       date: new Date(2023, 11, 12),
       time: "16:00",
       location: "Stade Municipal, Bordeaux",
       capacity: 5000,
       description: "Venez supporter votre équipe lors de ce match décisif.",
       image: "football_match.jpg",
       category: { id: 5, title: "Sport", description: "Événements sportifs, compétitions et matchs." },
     },
     {
       id: 6,
       title: "Spectacle de Théâtre",
       date: new Date(2023, 11, 15),
       time: "19:30",
       location: "Théâtre Municipal, Nice",
       capacity: 250,
       description: "Une pièce captivante qui vous tiendra en haleine.",
       image: "theatre_show.jpg",
       category: { id: 6, title: "Théâtre", description: "Représentations théâtrales et spectacles dramatiques." },
     },
     {
       id: 7,
       title: "Festival de Musique",
       date: new Date(2024, 0, 5),
       time: "12:00",
       location: "Parc des Expositions, Nantes",
       capacity: 10000,
       description: "Un festival avec plusieurs artistes sur scène.",
       image: "music_festival.jpg",
       category: { id: 7, title: "Festivals", description: "Festivals culturels, gastronomiques et musicaux." },
     },
     {
       id: 8,
       title: "Webinaire sur le Bien-être",
       date: new Date(2024, 0, 10),
       time: "18:00",
       location: "En ligne",
       capacity: 100,
       description: "Des conseils pour améliorer votre bien-être quotidien.",
       image: "wellness_webinar.jpg",
       category: { id: 8, title: "Webinaires", description: "Séminaires en ligne sur divers sujets." },
     },
     {
       id: 9,
       title: "Rencontre Professionnelle",
       date: new Date(2024, 0, 15),
       time: "15:00",
       location: "Hôtel de Ville, Strasbourg",
       capacity: 50,
       description: "Réseautage et échanges entre professionnels.",
       image: "networking_meeting.jpg",
       category: { id: 9, title: "Rencontres", description: "Événements de réseautage et de rencontres professionnelles." },
     },
     {
       id: 10,
       title: "Séminaire sur le Marketing Digital",
       date: new Date(2024, 0, 20),
       time: "10:00",
       location: "Bureau de Marketing, Lille",
       capacity: 30,
       description: "Apprenez les dernières tendances en marketing digital.",
       image: "digital_marketing_seminar.jpg",
       category: { id: 10, title: "Séminaires", description: "Séminaires éducatifs sur des thèmes spécifiques." },
     },
     {
       id: 11,
       title: "Concert de Jazz",
       date: new Date(2024, 0, 25),
       time: "21:00",
       location: "Club de Jazz, Paris",
       capacity: 100,
       description: "Un soir de jazz avec des musiciens talentueux.",
       image: "jazz_concert.jpg",
       category: { id: 1, title: "Concerts", description: "Événements musicaux en direct avec des artistes variés." },
     },
     {
       id: 12,
       title: "Exposition d'Art Contemporain",
       date: new Date(2024, 1, 1),
       time: "11:00",
       location: "Musée d'Art, Lyon",
       capacity: 150,
       description: "Explorez les dernières tendances en art contemporain.",
       image: "contemporary_art_exhibition.jpg",
       category: { id: 2, title: "Expositions", description: "Expositions d'art, de photographie et de culture." },
     },
     {
       id: 13,
       title: "Conférence sur l'Écologie",
       date: new Date(2024, 1, 5),
       time: "14:30",
       location: "Centre Écologique, Marseille",
       capacity: 200,
       description: "Discussions sur les enjeux écologiques actuels.",
       image: "ecology_conference.jpg",
       category: { id: 3, title: "Conférences", description: "Conférences sur des sujets divers et variés." },
     },
     {
       id: 14,
       title: "Atelier de Photographie",
       date: new Date(2024, 1, 10),
       time: "15:00",
       location: "Studio Photo, Toulouse",
       capacity: 10,
       description: "Améliorez vos compétences en photographie.",
       image: "photography_workshop.jpg",
       category: { id: 4, title: "Ateliers", description: "Ateliers pratiques pour développer de nouvelles compétences." },
     },
     {
       id: 15,
       title: "Compétition de Natation",
       date: new Date(2024, 1, 12),
       time: "09:00",
       location: "Piscine Municipale, Bordeaux",
       capacity: 300,
       description: "Participez à la compétition de natation annuelle.",
       image: "swimming_competition.jpg",
       category: { id: 5, title: "Sport", description: "Événements sportifs, compétitions et matchs." },
     },
     {
       id: 16,
       title: "Pièce de Théâtre Comique",
       date: new Date(2024, 1, 15),
       time: "20:00",
       location: "Théâtre Comique, Nice",
       capacity: 200,
       description: "Une comédie hilarante à ne pas manquer.",
       image: "comedy_show.jpg",
       category: { id: 6, title: "Théâtre", description: "Représentations théâtrales et spectacles dramatiques." },
     },
     {
       id: 17,
       title: "Festival de Gastronomie",
       date: new Date(2024, 2, 1),
       time: "11:00",
       location: "Centre Ville, Nantes",
       capacity: 5000,
       description: "Dégustez des plats de chefs renommés.",
       image: "gastronomy_festival.jpg",
       category: { id: 7, title: "Festivals", description: "Festivals culturels, gastronomiques et musicaux." },
     },
     {
       id: 18,
       title: "Webinaire sur la Productivité",
       date: new Date(2024, 2, 5),
       time: "17:00",
       location: "En ligne",
       capacity: 200,
       description: "Des astuces pour améliorer votre productivité.",
       image: "productivity_webinar.jpg",
       category: { id: 8, title: "Webinaires", description: "Séminaires en ligne sur divers sujets." },
     },
     {
       id: 19,
       title: "Salon de l'Emploi",
       date: new Date(2024, 2, 10),
       time: "09:00",
       location: "Palais des Congrès, Strasbourg",
       capacity: 1000,
       description: "Rencontrez des employeurs et trouvez un emploi.",
       image: "job_fair.jpg",
       category: { id: 9, title: "Rencontres", description: "Événements de réseautage et de rencontres professionnelles." },
     },
     {
       id: 20,
       title: "Séminaire sur la Finance Personnelle",
       date: new Date(2024, 2, 15),
       time: "14:00",
       location: "Centre Financier, Lille",
       capacity: 40,
       description: "Apprenez à gérer votre argent efficacement.",
       image: "personal_finance_seminar.jpg",
       category: { id: 10, title: "Séminaires", description: "Séminaires éducatifs sur des thèmes spécifiques." },
     },
     {
       id: 21,
       title: "Festival de Jazz",
       date: new Date(2024, 2, 20),
       time: "19:00",
       location: "Place de la République, Paris",
       capacity: 3000,
       description: "Un festival de jazz avec des artistes internationaux.",
       image: "jazz_festival.jpg",
       category: { id: 1, title: "Concerts", description: "Événements musicaux en direct avec des artistes variés." },
     },
     {
       id: 22,
       title: "Exposition de Sculpture",
       date: new Date(2024, 2, 25),
       time: "10:00",
       location: "Musée de Sculpture, Lyon",
       capacity: 100,
       description: "Découvrez des sculptures modernes et classiques.",
       image: "sculpture_exhibition.jpg",
       category: { id: 2, title: "Expositions", description: "Expositions d'art, de photographie et de culture." },
     },
     {
       id: 23,
       title: "Conférence sur la Santé",
       date: new Date(2024, 3, 1),
       time: "16:00",
       location: "Institut de Santé, Marseille",
       capacity: 150,
       description: "Discours sur les dernières avancées en santé.",
       image: "health_conference.jpg",
       category: { id: 3, title: "Conférences", description: "Conférences sur des sujets divers et variés." },
     },
     {
       id: 24,
       title: "Atelier de Peinture",
       date: new Date(2024, 3, 5),
       time: "14:00",
       location: "Studio d'Art, Toulouse",
       capacity: 12,
       description: "Exprimez votre créativité à travers la peinture.",
       image: "painting_workshop.jpg",
       category: { id: 4, title: "Ateliers", description: "Ateliers pratiques pour développer de nouvelles compétences." },
     },
   ];


